<#
.SYNOPSIS
    Post-processes DocFX-generated Markdown into Docusaurus-ready Markdown.

.DESCRIPTION
    This script converts raw DocFX Markdown into Markdown that can be consumed
    directly by the central Docusaurus documentation site.

    It:
      - Reads each .md file under -InputDir
      - Extracts the first H1 heading
      - Removes DocFX's leading <a id="..."></a> anchor from title metadata
      - Creates Docusaurus front matter
      - Preserves DocFX anchors inside the document body
      - Copies DocFX toc.yml / toc.yaml files unchanged
      - Optionally reads a Unity xrefmap.yml
      - Links inherited Unity API members to the matching Unity reference page
      - Repairs DocFX global-namespace Markdown links
      - Reports unresolved local Markdown links
      - Clears the output directory before writing
      - Fails clearly if input is missing, empty, malformed, or incomplete

.PARAMETER InputDir
    Directory containing raw DocFX Markdown.

    Default:
        docs-generated/docfx-raw

.PARAMETER OutputDir
    Directory where Docusaurus-ready Markdown will be written.

    Default:
        docs-generated/api

.PARAMETER UnityXrefMapPath
    Optional path to a Unity xrefmap.yml.

    When supplied, inherited Unity API members such as:

        Component.GetComponent(Type)

    can be linked to the corresponding Unity scripting reference page.

.PARAMETER StripKindPrefix
    If supplied, sidebar_label removes the leading DocFX API kind from titles.

    For example:

        Class DocumentationExample

    becomes:

        DocumentationExample

    and:

        Namespace Platformer.Gameplay

    becomes:

        Platformer.Gameplay

    The page title itself remains unchanged.
#>

[CmdletBinding()]
param(
    [string]$InputDir = "docs-generated/docfx-raw",
    [string]$OutputDir = "docs-generated/api",
    [string]$UnityXrefMapPath,
    [switch]$StripKindPrefix
)

$ErrorActionPreference = "Stop"

# ----------------------------------------------------------------------
# General helpers
# ----------------------------------------------------------------------

function Fail {
    param(
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-Error $Message
    exit 1
}

function Get-RelativePath {
    param(
        [Parameter(Mandatory)]
        [string]$BasePath,

        [Parameter(Mandatory)]
        [string]$FullPath
    )

    $resolvedBase = (Resolve-Path -LiteralPath $BasePath).Path
    $resolvedFull = (Resolve-Path -LiteralPath $FullPath).Path

    return [System.IO.Path]::GetRelativePath(
        $resolvedBase,
        $resolvedFull
    )
}

function Escape-YamlDoubleQuotedString {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    # YAML double-quoted strings use backslash escaping.
    $escaped = $Value.Replace('\', '\\')
    $escaped = $escaped.Replace('"', '\"')

    return $escaped
}

# ----------------------------------------------------------------------
# Unity xref support
# ----------------------------------------------------------------------

function Read-UnityXrefMap {
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        Fail "Unity xref map '$Path' does not exist."
    }

    Write-Host ""
    Write-Host "Reading Unity xref map..."

    # nameWithType is what most inherited-member text generated by DocFX
    # looks like, for example:
    #
    #   Object.FindObjectsOfType(Type)
    #   Component.GetComponent(Type)
    #
    # Map that display form directly to the external Unity documentation URL.
    $lookup = [System.Collections.Generic.Dictionary[string, string]]::new(
        [System.StringComparer]::Ordinal
    )

    $currentHref = $null
    $currentNameWithType = $null

    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path

    foreach ($line in [System.IO.File]::ReadLines($resolvedPath)) {

        # A new xref entry begins.
        #
        # Commit the previous entry before resetting our temporary state.
        if ($line.StartsWith("- uid: ")) {
            if (
                -not [string]::IsNullOrWhiteSpace($currentHref) -and
                -not [string]::IsNullOrWhiteSpace($currentNameWithType)
            ) {
                if (-not $lookup.ContainsKey($currentNameWithType)) {
                    $lookup.Add(
                        $currentNameWithType,
                        $currentHref
                    )
                }
            }

            $currentHref = $null
            $currentNameWithType = $null
            continue
        }

        if ($line.StartsWith("  href: ")) {
            $currentHref = $line.Substring(8).Trim()
            continue
        }

        if ($line.StartsWith("  nameWithType: ")) {
            $currentNameWithType = $line.Substring(16).Trim()
            continue
        }
    }

    # Commit the final xref entry.
    if (
        -not [string]::IsNullOrWhiteSpace($currentHref) -and
        -not [string]::IsNullOrWhiteSpace($currentNameWithType)
    ) {
        if (-not $lookup.ContainsKey($currentNameWithType)) {
            $lookup.Add(
                $currentNameWithType,
                $currentHref
            )
        }
    }

    if ($lookup.Count -eq 0) {
        Fail "Unity xref map '$Path' was read successfully but contained no usable nameWithType/href entries."
    }

    Write-Host "Unity xref entries loaded: $($lookup.Count)"

    return $lookup
}

function ConvertFrom-MarkdownEscapedMemberName {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    # DocFX Markdown escapes punctuation in inherited-member names.
    #
    # For example:
    #
    #   Object.FindObjectsOfType\(Type\)
    #
    # The Unity xref map contains:
    #
    #   Object.FindObjectsOfType(Type)
    #
    # Remove Markdown escaping for lookup purposes only. The displayed
    # Markdown text itself remains exactly as DocFX produced it.
    return [regex]::Replace(
        $Value,
        '\\([\\`*_{}\[\]()#+\-.!<>])',
        '$1'
    )
}

function Add-UnityInheritedMemberLinks {
    param(
        [Parameter(Mandatory)]
        [string]$OutputDir,

        [Parameter(Mandatory)]
        [System.Collections.Generic.Dictionary[string, string]]$XrefLookup
    )

    $linkedCount = 0

    $markdownFiles = @(
        Get-ChildItem `
            -LiteralPath $OutputDir `
            -Filter "*.md" `
            -Recurse `
            -File
    )

    foreach ($file in $markdownFiles) {

        $lines = @(
            Get-Content `
                -LiteralPath $file.FullName
        )

        $insideInheritedMembers = $false
        $changed = $false

        for ($index = 0; $index -lt $lines.Count; $index++) {

            $line = $lines[$index]

            # DocFX generates inherited members under this heading.
            if ($line -match '^####\s+Inherited Members\s*$') {
                $insideInheritedMembers = $true
                continue
            }

            # Any subsequent Markdown heading ends the inherited-member block.
            if (
                $insideInheritedMembers -and
                $line -match '^#{1,6}\s+'
            ) {
                $insideInheritedMembers = $false
            }

            if (-not $insideInheritedMembers) {
                continue
            }

            # Typical DocFX output:
            #
            #   Component.GetComponent\(Type\),
            #
            # Keep the trailing comma outside the generated Markdown link.
            if (
                $line -notmatch
                '^(?<indent>\s*)(?<member>.+?)(?<suffix>,\s*)$'
            ) {
                continue
            }

            $indent = $Matches["indent"]
            $memberMarkdown = $Matches["member"]
            $suffix = $Matches["suffix"]

            # Do not alter something DocFX has already linked.
            if ($memberMarkdown -match '^\[.*\]\(.*\)$') {
                continue
            }

            $lookupName = ConvertFrom-MarkdownEscapedMemberName `
                -Value $memberMarkdown

            if (-not $XrefLookup.ContainsKey($lookupName)) {
                continue
            }

            $href = $XrefLookup[$lookupName]

            $lines[$index] =
                "$indent[$memberMarkdown]($href)$suffix"

            $linkedCount++
            $changed = $true
        }

        if ($changed) {
            Set-Content `
                -LiteralPath $file.FullName `
                -Value $lines `
                -Encoding utf8
        }
    }

    return $linkedCount
}

# ----------------------------------------------------------------------
# DocFX global-namespace link repair
# ----------------------------------------------------------------------

function Repair-GlobalNamespaceLinks {
    param(
        [Parameter(Mandatory)]
        [string]$OutputDir
    )

    $markdownFiles = @(
        Get-ChildItem `
            -LiteralPath $OutputDir `
            -Filter "*.md" `
            -Recurse `
            -File
    )

    # Reference-type values allow the regex replacement callback to update
    # these counters without PowerShell scope surprises.
    $stats = @{
        RepairedCount   = 0
        UnresolvedLinks = [System.Collections.Generic.List[string]]::new()
    }

    foreach ($file in $markdownFiles) {

        $content = Get-Content `
            -LiteralPath $file.FullName `
            -Raw

        $fileDirectory = Split-Path -Parent $file.FullName

        # Match relative Markdown links such as:
        #
        #   [Foo](Foo.md)
        #   [Foo](Foo.md#some-anchor)
        #
        # Query strings and external URLs are deliberately not considered.
        $pattern = '\]\((?<path>[^)#?]+\.md)(?<fragment>#[^)]+)?\)'

        $newContent = [regex]::Replace(
            $content,
            $pattern,
            {
                param($match)

                $linkPath = $match.Groups["path"].Value
                $fragment = $match.Groups["fragment"].Value

                # DocFX can Markdown-escape punctuation inside targets.
                # Filesystem paths themselves do not contain those escapes.
                $filesystemLinkPath = $linkPath.Replace('\-', '-')

                # Ignore external URLs and absolute site-root links.
                if (
                    $linkPath -match '^[a-zA-Z][a-zA-Z0-9+.-]*://' -or
                    $linkPath.StartsWith('/')
                ) {
                    return $match.Value
                }

                $normalTarget = Join-Path `
                    $fileDirectory `
                    $filesystemLinkPath

                # The original target already exists.
                if (Test-Path -LiteralPath $normalTarget -PathType Leaf) {
                    return $match.Value
                }

                $linkDirectory = Split-Path -Parent $filesystemLinkPath
                $linkFileName = Split-Path -Leaf $filesystemLinkPath

                if ([string]::IsNullOrWhiteSpace($linkDirectory)) {
                    $globalLinkPath = "Global.$linkFileName"
                }
                else {
                    $globalLinkPath = Join-Path `
                        $linkDirectory `
                        "Global.$linkFileName"
                }

                $globalTarget = Join-Path `
                    $fileDirectory `
                    $globalLinkPath

                # DocFX sometimes references:
                #
                #   Foo.md
                #
                # even though the global-namespace page it emitted is:
                #
                #   Global.Foo.md
                if (Test-Path -LiteralPath $globalTarget -PathType Leaf) {

                    $stats.RepairedCount++

                    Write-Host (
                        "Repaired global link: " +
                        "$linkPath -> $globalLinkPath"
                    )

                    # Markdown paths should use forward slashes.
                    $globalLinkPath = $globalLinkPath.Replace('\', '/')

                    return "]($globalLinkPath$fragment)"
                }

                $stats.UnresolvedLinks.Add(
                    "$($file.Name): $linkPath$fragment"
                )

                return $match.Value
            }
        )

        if ($newContent -ne $content) {
            Set-Content `
                -LiteralPath $file.FullName `
                -Value $newContent `
                -NoNewline `
                -Encoding utf8
        }
    }

    return @{
        RepairedCount   = $stats.RepairedCount
        UnresolvedLinks = @($stats.UnresolvedLinks)
    }
}

# ----------------------------------------------------------------------
# Validate input
# ----------------------------------------------------------------------

if (-not (Test-Path -LiteralPath $InputDir -PathType Container)) {
    Fail "Input directory '$InputDir' does not exist. Did the DocFX generation step run?"
}

$mdFiles = @(
    Get-ChildItem `
        -LiteralPath $InputDir `
        -Filter "*.md" `
        -Recurse `
        -File
)

if ($mdFiles.Count -eq 0) {
    Fail "No Markdown files were found under '$InputDir'. DocFX output looks empty or invalid."
}

Write-Host "DocFX -> Docusaurus post-processing"
Write-Host "----------------------------------"
Write-Host "Input directory : $InputDir"
Write-Host "Output directory: $OutputDir"
Write-Host "Markdown files  : $($mdFiles.Count)"

if (-not [string]::IsNullOrWhiteSpace($UnityXrefMapPath)) {
    Write-Host "Unity xref map  : $UnityXrefMapPath"
}
else {
    Write-Host "Unity xref map  : not supplied"
}

# ----------------------------------------------------------------------
# Prepare clean output
# ----------------------------------------------------------------------

if (Test-Path -LiteralPath $OutputDir) {
    Write-Host ""
    Write-Host "Clearing existing output directory..."

    Remove-Item `
        -LiteralPath $OutputDir `
        -Recurse `
        -Force
}

New-Item `
    -ItemType Directory `
    -Path $OutputDir `
    -Force |
    Out-Null

# ----------------------------------------------------------------------
# Process Markdown files
# ----------------------------------------------------------------------

$errors = @()
$processedCount = 0

foreach ($file in $mdFiles) {

    $relativePath = Get-RelativePath `
        -BasePath $InputDir `
        -FullPath $file.FullName

    Write-Host "Processing: $relativePath"

    $content = Get-Content `
        -LiteralPath $file.FullName `
        -Raw

    if ([string]::IsNullOrWhiteSpace($content)) {
        $errors += "Empty Markdown file: $relativePath"
        continue
    }

    # Raw DocFX Markdown should not already contain Docusaurus front matter.
    #
    # Accept both LF and CRLF immediately after the opening delimiter.
    if ($content -match '^\uFEFF?---\r?\n') {
        $errors += "Unexpected existing front matter: $relativePath"
        continue
    }

    # DocFX normally emits:
    #
    #   # <a id="Namespace_Type"></a> Class Type
    #
    # but a conventional Markdown H1 is also accepted.
    $h1Match = [regex]::Match(
        $content,
        '(?m)^#\s+(.+?)\s*$'
    )

    if (-not $h1Match.Success) {
        $errors += "No H1 heading found: $relativePath"
        continue
    }

    $rawHeadingText = $h1Match.Groups[1].Value

    # Remove only the DocFX anchor from title metadata.
    #
    # The anchor remains in the document body because generated member links
    # depend on those anchors.
    $cleanTitle = [regex]::Replace(
        $rawHeadingText,
        '<a\s+id="[^"]*"\s*>\s*</a>\s*',
        ''
    )

    # Defensive cleanup in case some other inline HTML appears in the H1.
    $cleanTitle = [regex]::Replace(
        $cleanTitle,
        '<[^>]+>',
        ''
    ).Trim()

    if ([string]::IsNullOrWhiteSpace($cleanTitle)) {
        $errors += (
            "H1 resolved to an empty title after cleanup: " +
            $relativePath
        )

        continue
    }

    $sidebarLabel = $cleanTitle

    if ($StripKindPrefix) {
        $sidebarLabel = [regex]::Replace(
            $sidebarLabel,
            '^(Class|Struct|Interface|Enum|Delegate|Namespace)\s+',
            ''
        )
    }

    if ([string]::IsNullOrWhiteSpace($sidebarLabel)) {
        $errors += (
            "Sidebar label resolved to an empty string: " +
            $relativePath
        )

        continue
    }

    $titleYaml = Escape-YamlDoubleQuotedString $cleanTitle
    $labelYaml = Escape-YamlDoubleQuotedString $sidebarLabel

    $frontMatter = @"
---
title: "$titleYaml"
sidebar_label: "$labelYaml"
---

"@

    $newContent = $frontMatter + $content

    $targetPath = Join-Path `
        $OutputDir `
        $relativePath

    $targetDirectory = Split-Path `
        -Parent `
        $targetPath

    if (-not (Test-Path -LiteralPath $targetDirectory)) {
        New-Item `
            -ItemType Directory `
            -Path $targetDirectory `
            -Force |
            Out-Null
    }

    Set-Content `
        -LiteralPath $targetPath `
        -Value $newContent `
        -NoNewline `
        -Encoding utf8

    $processedCount++
}

# ----------------------------------------------------------------------
# Copy support files
# ----------------------------------------------------------------------

$supportFiles = @(
    Get-ChildItem `
        -LiteralPath $InputDir `
        -Recurse `
        -File |
    Where-Object {
        $_.Name -ieq "toc.yml" -or
        $_.Name -ieq "toc.yaml"
    }
)

foreach ($supportFile in $supportFiles) {

    $relativePath = Get-RelativePath `
        -BasePath $InputDir `
        -FullPath $supportFile.FullName

    $targetPath = Join-Path `
        $OutputDir `
        $relativePath

    $targetDirectory = Split-Path `
        -Parent `
        $targetPath

    if (-not (Test-Path -LiteralPath $targetDirectory)) {
        New-Item `
            -ItemType Directory `
            -Path $targetDirectory `
            -Force |
            Out-Null
    }

    Copy-Item `
        -LiteralPath $supportFile.FullName `
        -Destination $targetPath `
        -Force

    Write-Host "Copied support file: $relativePath"
}

# ----------------------------------------------------------------------
# Link inherited Unity API members
# ----------------------------------------------------------------------

$unityLinkedMemberCount = 0

if (-not [string]::IsNullOrWhiteSpace($UnityXrefMapPath)) {

    $unityXrefLookup = Read-UnityXrefMap `
        -Path $UnityXrefMapPath

    $unityLinkedMemberCount = Add-UnityInheritedMemberLinks `
        -OutputDir $OutputDir `
        -XrefLookup $unityXrefLookup
}

# ----------------------------------------------------------------------
# Repair DocFX global-namespace links
# ----------------------------------------------------------------------

$linkRepairResult = Repair-GlobalNamespaceLinks `
    -OutputDir $OutputDir

$repairedLinkCount = $linkRepairResult.RepairedCount
$unresolvedLinks = @($linkRepairResult.UnresolvedLinks)

if ($unresolvedLinks.Count -gt 0) {

    Write-Host ""
    Write-Host `
        "Unresolved local Markdown links:" `
        -ForegroundColor Yellow

    foreach ($unresolvedLink in $unresolvedLinks) {
        Write-Host `
            "  - $unresolvedLink" `
            -ForegroundColor Yellow
    }
}

# ----------------------------------------------------------------------
# Final validation
# ----------------------------------------------------------------------

if ($errors.Count -gt 0) {

    Write-Host ""

    Write-Host `
        "Encountered $($errors.Count) problem file(s):" `
        -ForegroundColor Red

    foreach ($errorMessage in $errors) {
        Write-Host `
            "  - $errorMessage" `
            -ForegroundColor Red
    }

    Fail (
        "Post-processing failed validation. " +
        "Wrote $processedCount of $($mdFiles.Count) Markdown file(s) " +
        "before validation completed."
    )
}

if ($processedCount -ne $mdFiles.Count) {
    Fail (
        "Expected to process $($mdFiles.Count) Markdown file(s), " +
        "but processed $processedCount."
    )
}

$outputMarkdownFiles = @(
    Get-ChildItem `
        -LiteralPath $OutputDir `
        -Filter "*.md" `
        -Recurse `
        -File
)

if ($outputMarkdownFiles.Count -ne $mdFiles.Count) {
    Fail (
        "Output validation failed. " +
        "Expected $($mdFiles.Count) Markdown file(s), " +
        "found $($outputMarkdownFiles.Count)."
    )
}

# ----------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------

Write-Host ""
Write-Host "Post-processing complete."
Write-Host "Processed Markdown files : $processedCount"
Write-Host "Copied support files     : $($supportFiles.Count)"
Write-Host "Unity members linked     : $unityLinkedMemberCount"
Write-Host "Global links repaired    : $repairedLinkCount"
Write-Host "Unresolved local links   : $($unresolvedLinks.Count)"
Write-Host "Output directory         : $OutputDir"
